kind: pipeline
type: docker
name: integration

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - dotnet sonarscanner begin /k:"easv-devops_MichaelDrone_AY3rF325EVvRW2O60ERL" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_eacb3b050e201c91f790c01434e0ed41a6ca0530" 
      - dotnet build 
      - dotnet sonarscanner end /d:sonar.token="sqp_eacb3b050e201c91f790c01434e0ed41a6ca0530"